### ISSUE TITLE
I can't get completion.

### ISSUE THREAD

**Issue by ColMugX** [posva/vim-vue#101]
![image](https://user-images.githubusercontent.com/21327913/36706975-450351e6-1ba7-11e8-96e4-df6ea03314c6.png)

`$` can't get anything. How can I do?

I'm using `LanguageClient-neovim` and install `vue-language-server` globally.

**Comment by ColMugX** [comment]
![image](https://user-images.githubusercontent.com/21327913/36715955-8e10883c-1bd3-11e8-98d9-bf2fa23846a5.png)

now getting a new problem. The highlight broken

**Comment by ColMugX** [comment]
@adriaanzon 

yeah, thanks. 

I solved about the highlighting, but the completion none.

**Comment by adriaanzon** [comment]
This plugin doesn't provide completion so maybe you're better off asking over at one of the other projects you mentioned.

A quick google search led me to [this](https://github.com/vuejs/vetur/tree/master/server#usage) though. Have you configured LanguageClient-neovim correctly?

**Comment by ColMugX** [comment]
@adriaanzon 

Yes, I configured well actually, it can show others for vue but not about `$`.

**Comment by ColMugX** [comment]
@HerringtonDarkholme 

Excuse me, Can I get help?

**Comment by HerringtonDarkholme** [comment]
Please report the issue to vuejs/vetur and provide a reproduction project.

Thanks.

**Comment by ColMugX** [comment]
Sorry..

And thank you for your help.
