### ISSUE TITLE
Syntax checker stopped working for Vue files

### ISSUE THREAD

**Issue by PVince81** [posva/vim-vue#103]
When saving a "vue" file, the following error appears in the console:
```
Error detected while processing function 77[1]..10:
line   18:
E700: Unknown function: SyntaxCheckers_javascript_eslint_GetLocList
Error detected while processing function <SNR>34_BufWritePostHook[3]..<SNR>34_UpdateErrors[13]..<SNR>34_CacheErrors[34]..16[1]..15:
line    3:
E15: Invalid expression: self._locListFunc()
Error detected while processing function <SNR>34_BufWritePostHook[3]..<SNR>34_UpdateErrors[13]..<SNR>34_CacheErrors:
line   34:
E170: Missing :endfor
Error detected while processing function <SNR>34_BufWritePostHook[3]..<SNR>34_UpdateErrors:
line   13:
E171: Missing :endif
```

### Vue file
```
<template>
<div class="monitor">
	<div>Monitor</div>
	<monitor />
</div>
</template>

<script>

import Monitor from './components/Monitor.vue'

export default {
	components: { Monitor },
	data () {
		return {
			msg: 'Hello from vue-loader!'
		}
	}
}
</script>

<style>
.message {
	color: blue;
}
</style>
```

### NPM eslint
```
± % npm ls -g | grep eslint
├─┬ eslint@4.18.2
│ ├─┬ eslint-scope@3.7.1
│ ├── eslint-visitor-keys@1.0.0
├── eslint-config-standard@11.0.0
├─┬ eslint-plugin-html@4.0.2
├─┬ eslint-plugin-import@2.9.0
│ ├─┬ eslint-import-resolver-node@0.3.2
│ ├─┬ eslint-module-utils@2.1.1
├─┬ eslint-plugin-node@6.0.1
├── eslint-plugin-promise@3.7.0
├── eslint-plugin-standard@3.0.1
├─┬ eslint-plugin-vue@4.3.0
│ └─┬ vue-eslint-parser@2.0.3
│   ├─┬ eslint-scope@3.7.1
│   ├── eslint-visitor-keys@1.0.0
```

### Variables
- g:loaded_syntastic_vue_eslint_checker is 1
- g:loaded_syntastic_javascript_eslint_checker is not defined

Is "g:loaded_syntastic_javascript_eslint_checker" supposed to be 1 so that vim-vue can redirect to it ?

From what I see the missing function `SyntaxCheckers_javascript_eslint_GetLocList` is defined in "Syntastic/syntax_checkers/javascript/eslint.vim" and likely not loaded because the above variable is not set.

Is vim even supposed to go there or should it call a different function ?

How to debug this ?

**Comment by PVince81** [comment]
some vars from vimrc:

```
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_python_checkers = ['pylint']
let g:syntastic_php_checkers = ['php', 'phpcs', 'phpmd']
let g:syntastic_aggregate_errors = 1
let g:syntastic_php_phpcs_args = "--standard=$HOME/.phpcs.xml --report=csv --tab-width=4"
let g:syntastic_php_phpmd_post_args = "codesize,design,unusedcode"
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_javascript_jshint_args = '--config /home/vincent/.jshintrc'
```

**Comment by PVince81** [comment]
replacing "jshint" with
```
let g:syntastic_javascript_checkers = ['eslint']
```

doesn't help either.

When running eslint on the file from the CLI:
```
± % eslint src/App.vue 

src/App.vue
  8:1  error  Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag

✖ 1 problem (1 error, 0 warnings)
```


If I open a regular JS file then the variable `g:loaded_syntastic_javascript_eslint_checker` is defined and the checker works.

So maybe the vue plugin is doing something that prevents the regular eslint checker to enable itself ?

**Comment by PVince81** [comment]
This is with vim-vue from master, sitting on commit a2791727525fe28241d82c8d463bfdef68c3e2c5

**Comment by adriaanzon** [comment]
I don't have time to look at this right now but it looks related to https://github.com/posva/vim-vue/issues/83

**Comment by PVince81** [comment]
I don't think it's directly related, see the very first error: it looks like some issue with plugin loading when opening Vue files, as this error doesn't appear when opening JS files directly.

I'm using vundle and have the line `Bundle posva/vim-vue` after most of the other bundles.

**Comment by PVince81** [comment]
Just tried on another computer and it's happening as well. Instead of openSUSE Tumbleweed it's openSUSE Leap 42.3.

If you say that all works fine on your side then I might need to debug on my side. Unfortunately I don't have any experience with vimscript or debugging vim, so if you have any pointers what I could try (add print statements?) I might be able to help.

**Comment by PVince81** [comment]
After looking at some code online I found something that seems to load the eslint file, so this patch makes the error disappear:
```
--- a/syntax_checkers/vue/eslint.vim
+++ b/syntax_checkers/vue/eslint.vim
@@ -6,6 +6,8 @@ endif
 
 let g:loaded_syntastic_vue_eslint_checker = 1
 
+runtime! syntax_checkers/javascript/eslint.vim
+
 call g:SyntasticRegistry.CreateAndRegisterChecker({
       \   'filetype': 'vue',
       \   'name': 'eslint',
```

I think this would force loading "javascript/eslint.vim" which seems to be not loaded in my editor for some reason when opening "vue" files.

Does this make any sense ?


Now at this point it says "unexpected token <" for the "<template>" tag, so it's probably checking the whole file with eslint instead of just some blocks.

**Comment by PVince81** [comment]
ok, the "unexpected token" also happens when running "eslint" on the CLI.

In any case, the patch from https://github.com/posva/vim-vue/issues/103#issuecomment-378598530 seems to fix my issue, should I submit it as PR ? As I don't understand vimscript I cannot judge whether it makes sense or not but at least it makes it work for me.

It was inspired by https://github.com/vim-syntastic/syntastic/pull/926/files#diff-09905128bc99e5d00aaf91cc9433a245R19

**Comment by PVince81** [comment]
PR here https://github.com/posva/vim-vue/pull/105
