### ISSUE TITLE
Syntastic will not use local eslint even while using mtscout6/syntastic-local-eslint.vim

### ISSUE THREAD

**Issue by hacktivista** [posva/vim-vue#106]
Syntastic / EsLint syntax checking is not being triggered on .vue files, but it is being triggered on .js files.

Below you can see an screenshot of both filetypes with "the same content" (difference is that template is embedded in JS in the second case).

![image](https://user-images.githubusercontent.com/5282749/38865408-0bd44a04-4214-11e8-863f-1914771ce439.png)

Here my relevant config:
```
"""""""""""
" vim-plug
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/syntastic'
Plug 'mtscout6/syntastic-local-eslint.vim'
Plug 'pangloss/vim-javascript'
Plug 'posva/vim-vue'

call plug#end()
" /vim-plug
"""""""""""

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_html_tidy_args = '--custom-tags yes'

filetype on
filetype plugin indent on
syntax on
set path=$PWD/** " Set path to current path, useful for :find
```

Help plz, I really need to keep moving but this has got me stuck a lot of time :(

**Comment by Hacktivista** [comment]
I want to make it clear that I've already tried deleting 'mtscout6/syntastic-local-eslint.vim' and installing eslint globally, same results.

**Comment by Hacktivista** [comment]
Guys, it definetly has to do with 'mtscout6/syntastic-local-eslint.vim' plugin, I tried it before, but tried it wrong... Will need to check if one can bypass this error somehow.

**Comment by Hacktivista** [comment]
As a workaround you can use [nodeenv](https://github.com/ekalinin/nodeenv) and install project related eslint packages "globally" within a packed environment... If you have other solution post it here!!

**Comment by adriaanzon** [comment]
That plugin doesn't work with Vue files because it sets `b:syntastic_javascript_eslint_exec`. It needs to set `b:syntastic_vue_eslint_exec`, for it to work with Vue files.
