### ISSUE TITLE
Styles highlighting broken by splitting <style> tag into multiple lines

### ISSUE THREAD

**Issue by robertjk** [posva/vim-vue#108]
When `<style scoped lang="scss">` delcaration is on a single line, the syntax highlighting works fine:

![singleline](https://user-images.githubusercontent.com/12070821/40542367-34a1237e-6020-11e8-95c9-376de20f9171.png)

But I like to split all multi-attributes tags into separate lines. If I do it, the highlighting gets broken (notice that Sass attributes are not properly highlighted anymore):

![multiline](https://user-images.githubusercontent.com/12070821/40542393-45735eec-6020-11e8-9a21-f4c3529dea50.png)

As that's a valid HTML, I would expect the highlighting not get broken by this.

**Comment by adriaanzon** [comment]
The matching pattern assumed a space after the tag name. I fixed it by changing the space to a word boundary.

**Comment by robertjk** [comment]
Oh yeah, I understand. Thank you for submitting the correction :).
