### ISSUE TITLE
No such variable: "b:current_syntax"

### ISSUE THREAD

**Issue by jesstelford** [posva/vim-vue#11]
Using Pathogen to load, on commit 4adfb9b, when opening a `.vue` file, I get the following error in vim:

```
Error detected while processing /path/to/.vim/bundle/vim-vue/syntax/vue.vim:
line   72:
E108: No such variable: "b:current_syntax"
```

The syntax highlighting still appears to work (although, this is my first time with vue, so I'm not 100% what I'm looking at).

**Comment by posva** [comment]
Are you using pug (jade) for html. Do you have only one vim plugin for pug?

**Comment by posva** [comment]
@jesstelford Any updates?

**Comment by jesstelford** [comment]
A quick check in my bundles reveals only the following:

```bash
$ ack "jade" -l
vim-vue/readme.md
vim-vue/syntax/vue.vim
syntastic/syntax_checkers/jade/jade_lint.vim
syntastic/plugin/syntastic/registry.vim
$ ack "pug" -l
vim-vue/readme.md
vim-vue/syntax/vue.vim
syntastic/syntax_checkers/pug/pug_lint.vim
syntastic/syntax_checkers/jade/jade_lint.vim
syntastic/plugin/syntastic/registry.vim
```

Is there a prerequisite to have a pug syntax highlighter installed? Does vue rely on pug?

Note I am still getting same error on commit `922f01c`

**Comment by jesstelford** [comment]
To be specific, this is an example of a file which exhibits the error: https://github.com/ferry77/hcard-vue/blob/master/src/hCardBuilder.vue

**Comment by posva** [comment]
I think the problem is with the vim less plugin. I use this one groenewege/vim-less, which one do you use?

**Comment by jesstelford** [comment]
I don't have any less plugins installed, only rules for syntastic.

```bash
$ find ./ -iname "less"
./syntastic/syntax_checkers/less
```

If I get some more time, I'll do some isolation tests to figure out what the bad mix is.

**Comment by posva** [comment]
The line failing is related to less, thats why I'm asking. Vim vue doesn't need the other plug-ins but rely on them for syntax
I've been unable to reproduce it so if you can isolate the problem, that would be great ☺

**Comment by jonas8** [comment]
same problem on[ line 60](https://github.com/posva/vim-vue/blob/master/syntax/vue.vim#L60).

**Comment by Armoletti** [comment]
Also got the error from line 60. Disabling pluging "gorodinskiy/vim-coloresque" removed the error.

**Comment by jonas8** [comment]
@Armoletti thanks. works, and use [`lilydjwg/colorizer`](https://github.com/lilydjwg/colorizer) instead of `gorodinskiy/vim-coloresque`

**Comment by dsdeiz** [comment]
I'm also getting similar error:

> Error detected while processing ~/.vim/plugged/javascript-libraries-syntax.vim/after/syntax/coffee.vim:
line    8:
E121: Undefined variable: b:current_syntax
E15: Invalid expression: b:current_syntax == 'coffee'
Error detected while processing ~/.vim/plugged/vim-vue/syntax/vue.vim:
line   49:
E108: No such variable: "b:current_syntax"
