### ISSUE TITLE
strange highlighting behaviour

### ISSUE THREAD

**Issue by javidh** [posva/vim-vue#110]
Sometimes, some lines are formatted like this: 

![image](https://user-images.githubusercontent.com/6296082/42113211-78fc8f46-7bb8-11e8-94b4-790498779b71.png)

I have no idea what's going on. The highlights at the beginning of the line makes no sense.

**Comment by clee-jana** [comment]
@javidh those are very likely tabs?

**Comment by javidh** [comment]
@clee-jana no they are not. They are just spaces. like the correctly unhighlightted ones.

**Comment by adriaanzon** [comment]
I think it is related to https://github.com/posva/vim-vue/issues/102#issuecomment-373453197
