### ISSUE TITLE
It seems that can’t work with dein enviroment?

### ISSUE THREAD

**Issue by aniude** [posva/vim-vue#117]
My .bashrc

```
call dein#add(‘postal/vim-vue’)
let g:vue_disable_pre_processors=0
autocmd BufRead,BufNewFile *.vue setlocal filetype=vue.html,JavaScript.css
```

**Comment by posva** [comment]
it's `posva/vim-vue`
you shouldn't need `autocmd BufRead,BufNewFile *.vue setlocal filetype=vue.html,JavaScript.css`

**Comment by aniude** [comment]
@posva my spell typo for this MR.
My .bashrc

`
call dein#add('posva/vim-vue')
let g:vue_disable_pre_processors=0   
`
It still don’t work. 
Is that other config with conflict?

**Comment by posva** [comment]
You don't say _what isn't working_, there is no way for anybody to help you if you say nothing else...

**Comment by aniude** [comment]
Thanks, I found the problem. The other theme conflict. But the priority more than vim-vue.
