### ISSUE TITLE
Disable Tag Brackets highligting

### ISSUE THREAD

**Issue by christophwolff** [posva/vim-vue#130]
Hi! First of all: Thank you for the awesome Plugin!

I wonder if there is an option to disable the highlight when i hover  `<` or `>` with the cursor.

<img width="418" alt="bildschirmfoto 2019-02-11 um 16 45 00" src="https://user-images.githubusercontent.com/2046613/52574451-a09b3900-2e1c-11e9-82e6-3c5e836c755a.png">

Thank you.

**Comment by adriaanzon** [comment]
This is a standard Vim plugin.

From `:h matchparen`:

```
You can avoid loading this plugin by setting the "loaded_matchparen" variable: >
	:let loaded_matchparen = 1
```

**Comment by christophwolff** [comment]
Thank you!
`let g:loaded_matchparen = 1` in .vimrc worked for me 👍
