### ISSUE TITLE
Comma inserts '>' instead of actual comma

### ISSUE THREAD

**Issue by ricvillagrana** [posva/vim-vue#132]
When I try to set a comma (,) in Vue files it replaces it for ">".

Example:
```javascript
const obj = {
  name: 'John'> // Here I pressed <comma> (,) and then <Enter>

}
```

My .vimrc
```bash
" Vue config
let g:vim_vue_plugin_load_full_syntax = 1
let g:vim_vue_plugin_debug = 1
let g:vue_disable_pre_processors = 1
autocmd FileType vue syntax sync fromstart
```

**Comment by adriaanzon** [comment]
Vim-vue doesn't map the `,` key. Do you have other plug-ins installed? 

What's the output of `:verbose imap ,`?

**Comment by ricvillagrana** [comment]
Yes, I supposed that, but this only happens when a Vue file is opened, the `:verbose imap ,` returns `No mapping found`.
I will keep tracking the issue in my .vimrc.

**Comment by ricvillagrana** [comment]
I found the problem, I had installed `alvan/vim-closetag` and did not realize that it mapped the comma.
