### ISSUE TITLE
Html data attribute doesn't highlight correctly

### ISSUE THREAD

**Issue by amerov** [posva/vim-vue#136]
![Screenshot from 2019-06-19 22-31-46](https://user-images.githubusercontent.com/196747/59787071-1d19b900-92e2-11e9-9e76-7f0314030c64.png)

**Comment by laurentbardin** [comment]
Which of these attributes aren't correctly higlighted? Are you talking about the `data-*` attributes?

AFAIK, any non standard attribute is not highlighted the same way as a standard one (`href`, `src`, `class`, etc.). Data attributes are a special case in that the `data-` part is standard in HTML5, what follows is free form and therefore higlighted differently. That's how the default vim HTML syntax works, anyway.

So everything looks fine to me here. Am I missing anything?
