### ISSUE TITLE
% to jump to matching { or } doesn't work in <script> section

### ISSUE THREAD

**Issue by pmorch** [posva/vim-vue#137]
If I have a Foo.vue containing:

    <script>
        export default {
            methods: {
                foo() {
                }
            },
        }
    </script>

Then I expect to be able to put the cursor on the `{` after `export default`, hit `%` and have the cursor repositioned on the last `}`  just before `</script>`. That doesn't work. It sometimes works the very first time I try `%`  but not thereafter.

It does work after a `:set filetype=javascript`.

**Comment by adriaanzon** [comment]
I remember having this issue too for some filetypes.. https://github.com/neovim/neovim/issues/4051

Though I'm not sure if this is the same. Does it go away when you run `:MatchDebug`?

**Comment by pmorch** [comment]
Yup. It really sounds like it is the same issue. I'll close this issue.

**Comment by pmorch** [comment]
Hi,

Reopening - sorry for the noise. It looks like a similar problem - but it is not the same problem. The problem described in neovim/neovim#4051 is about markdown files, and although the symptoms sound similar, doing like it says in [[patch] matchit stops working after first use in markdown files - Google Groups](https://groups.google.com/forum/#!topic/vim_dev/wT28u7JLhUk)

> ensure to have sourced the matchit plugin and then open CONTRIBUTING.md
> file in Vim source tree, and go to this line :
> 
> [on the Vim website]: http://www.vim.org/maillist.php#vim-dev
> 
> :10
> Now press % on the first '[' bracket. Note, it will jump to the
> corresponding closing bracket. Press '%' again and note, that the cursor
> did not jump. 

I do not have this problem. Markdown works fine. So it is a similar problem, but not the same problem. Also, I'm running vim 8.0, but I just tried downloading and building vim HEAD and the problem is still there. I don't think it is the same problem as neovim/neovim#4051.

Can anybody else reproduce it?

**Comment by laurentbardin** [comment]
Hi @pmorch,

I can't reproduce the issue here, `%` works fine every time I use it with `syntax=vue`. I'm using the `matchit` plugin, are you? When your cursor is on one of the paired characters, is the other one correctly highlighted? You can activate/deactivate this with `:DoMatchParen`/`:NoMatchParen` (standard plugin).

This is what I have using your example code:

![matched-pairs](https://user-images.githubusercontent.com/1110159/62031076-d1163a00-b1e6-11e9-9e39-b6113859540f.png)

**Comment by dmix** [comment]
My html.vim supports this natively, the `matchit` plugin helps for sure, but it's something to keep in mind.

thanks @laurentbardin

**Comment by pmorch** [comment]
I've reduced the problem to the smallest example I could. It was an interaction with an out-of-date vim-matchit plugin. I was using an [out-of-date URL](https://github.com/geoffharcourt/vim-matchit) for the matchit plugin. Once i started using a better matchit URL, https://github.com/benjifisher/matchit.zip, the problem went away.

# Boring Old Details

They don't really matter now that I know the origin of my problem - the out-of-date matchit URL. But I've kept them here for posterity.

Ok here is how to reproduce this:

Start with a newly installed, fully-up-to-date installation from Xubuntu 18.04.1 media.
```
apt install git vim-gtk curl
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```
This `.vimrc`:
```
call plug#begin('~/.vim/plugged')
Plug 'geoffharcourt/vim-matchit'
Plug 'posva/vim-vue'
call plug#end()
```

This `Foo.vue`:
```
<script>
    export default {
        methods: {
            foo() {
            }
        },
    }
</script>
```

Open vim, type:
```
:PlugInstall
:e Foo.vue
```

Now putting the cursor on the `{` char at the end of `methods: {` and hidding `%` moves to the matching `}` exactly once.
