### ISSUE TITLE
Setting filetype for vue files

### ISSUE THREAD

**Issue by last-partizan** [posva/vim-vue#138]
In recent update of vim-git they added
```
au BufNewFile,BufRead *.vue			setf vuejs
```
https://github.com/vim/vim/commit/396e829fa355ebc92a618ef18266a3fed71b7042

And this plugin has stopped working.

How this can be fixed?

**Comment by redeyes2015** [comment]
I am putting `autocmd FileType vuejs set filetype=vue` in `~/.vimrc` to work around.

But I am also curious what to solve this issue properly.

**Comment by adriaanzon** [comment]
Has been fixed upstream https://github.com/vim/vim/commit/4248111497ab78f45d3d48576740949778a1e76b, https://github.com/vim/vim/commit/c273405188cc2f19e949089cda1f92bd81610dac
