### ISSUE TITLE
vim 8 install: eslint.vim: E121: Undefined variable: g:SyntasticRegistry

### ISSUE THREAD

**Issue by ryanrca** [posva/vim-vue#141]
Installed on vim 8 with the built in package manager:
```
> cd ~/.vim/plugin
> git clone https://github.com/posva/vim-vue.git
```

I restarted vim and get this error:
``` > vi ./Invoice.vue 
Error detected while processing /home/ryan/.vim/plugin/vim-vue/syntax_checkers/vue/eslint.vim:
line   15:
E121: Undefined variable: g:SyntasticRegistry
Press ENTER or type command to continue
```

For kicks, I installed the node eslint:
``` > npm i -g eslint eslint-plugin-vue```

But I get the same error.

**Comment by Ansa211** [comment]
I think it should be `cd ~/.vim/plugins/start` rather than `cd ~/.vim/plugin`

**Comment by ryanrca** [comment]
That seemed to fix it.  Thanks.
