### ISSUE TITLE
highlighting vue directive syntax

### ISSUE THREAD

**Issue by nicolidin** [posva/vim-vue#144]
Hello !

Does your plugin provide an improvement in the syntax of the view directives?
Is it possible to have the same directives syntax highlighting as vscode ?
The first screen below is my vim screen and the second is my vscode screen (with correct non string directive highlight syntax)

![vim-vue-screen](https://user-images.githubusercontent.com/37144206/69983507-2799d900-1537-11ea-8414-29e62c598d51.png)
![vscode-vue-screen](https://user-images.githubusercontent.com/37144206/69983538-3c766c80-1537-11ea-9daf-34bd54b2456e.png)

Hope you will have an answer, it would help me a lot, thank you !

**Comment by adriaanzon** [comment]
see #143
