### ISSUE TITLE
support more file type

### ISSUE THREAD

**Issue by L-Jovi** [posva/vim-vue#146]
I want to open `*.cml` file (the custom template lang) as `*.vue` behaviour, how should I support `*.cml` file type in vim-vue plugin?

**Comment by adriaanzon** [comment]
I'm not familiar with .cml files but if they have the same structure as Vue files, you can take the configuration from [ftdetect/vue.vim](https://github.com/posva/vim-vue/blob/master/ftdetect/vue.vim), modify it to support `*.cml`, and put it in your vimrc:

```vim
autocmd BufNewFile,BufRead *.cml setf vue
```
