### ISSUE TITLE
dynamically changing filetype?

### ISSUE THREAD

**Issue by GopherJ** [posva/vim-vue#147]

**Comment by GopherJ** [comment]
curently while working on a vue file, no matter where am I, the filetype is always `vue` which isn't ideal, because when I pass to `script` it should switch to `javascript` so that we can disable `emmet`

**Comment by adriaanzon** [comment]
When changing the filetype from vue to e.g. javascript when you're in a script tag, the contents of the surrounding template and style tags would lose their syntax highlighting, which is undesirable.

Using [context_filetype.vim](https://github.com/Shougo/context_filetype.vim) you could detect if the current section of the file is javascript, html or css. This doesn't change the `filetype` setting in vim, so context_filetype.vim should be manually implemented in plugins that benefit from it.
