### ISSUE TITLE
very very slow with othree/yajs.vim

### ISSUE THREAD

**Issue by stephanedemotte** [posva/vim-vue#16]
Hi !

Thanks for this syntax !

`.vue` file is very very slow with with [othree/yajs.vim](https://github.com/othree/yajs.vim)

Do you know how i can get `yajs.vim` for js file, but deactive it in `.vue` files ?

Thanks !

**Comment by posva** [comment]
Hello
You're very welcome
yajs seems to be slow on its own: https://github.com/othree/yajs.vim#performance-issue
Although the vue multi syntax  doesn't help 😞 
Maybe loading vue plugin before yajs. You may also have to include another javascript vim plugin

**Comment by maurop123** [comment]
Happy to have found this. After removing yajs.vim, vim is not crippling slow anymore. What a relief!
