### ISSUE TITLE
Which commenting plugin supports different comment style for file regions?

### ISSUE THREAD

**Issue by xream** [posva/vim-vue#17]
With [scrooloose/nerdcommenter](https://github.com/scrooloose/nerdcommenter) all I get is `/* */`

**Comment by posva** [comment]
Hello, this is something that has to be done in nerdcommenter side. There're two issues about it:
https://github.com/scrooloose/nerdcommenter/issues/225
https://github.com/scrooloose/nerdcommenter/issues/17

**Comment by xream** [comment]
@posva I see. I was just wondering what plugin you guys use.

**Comment by posva** [comment]
@xream I find myself with the same issue 😢

**Comment by bennettrogers** [comment]
I've been trying to improve my vue handling in vim as well. I just stumbled across [tcomment](https://github.com/tomtom/tcomment_vim) and tried replacing vim-commentary with it, and it seems to work well for me. I have to `set filetype=html` to get it to work properly, but now commenting works in the html, javascript, and css regions of a .vue file.

I need to keep using it to see if there are side effects, and I need to figure out a way to get correct syntax highlighting in the javascript region (syntax highlighting works, but it's not as good as what I get in a standalone javascript file).

**Comment by posva** [comment]
`ft=html` works well for js, html and css. However if you're using a
preprocessor like pug,  sass or stylus, you'll need something like vim-vue

**Comment by bennettrogers** [comment]
I do have vim-vue installed as well... Is it not actually doing anything if the filetype isn't set to vue?

I do use sass inside the style region of my .vue files. What functionality is lost there by setting `ft=html`?

**Comment by posva** [comment]
If you don't set the ft, it's not changing anything
Some of the syntax highlighting may not work on html

**Comment by nemtsov** [comment]
**Note for anyone finding this closed issue in the future:**

@xream [added hooks to NERDCommenter](https://github.com/scrooloose/nerdcommenter/pull/249) to allow switching to different comment delimiters, depending on the region of the `.vue` file.

Add the following to your `.vimrc` to enable it:

```vim
let g:ft = ''
fu! NERDCommenter_before()
  if &ft == 'vue'
    let g:ft = 'vue'
    let stack = synstack(line('.'), col('.'))
    if len(stack) > 0
      let syn = synIDattr((stack)[0], 'name')
      if len(syn) > 0
        let syn = tolower(syn)
        exe 'setf '.syn
      endif
    endif
  endif
endfu
fu! NERDCommenter_after()
  if g:ft == 'vue'
    setf vue
    g:ft
  endif
endfu
```

**Comment by kba** [comment]
@nemtsov Thanks for the hooks, works perfectly. I think the `g:ft` in the third-to-last line is a typo though.

**Comment by Val-istar-Guo** [comment]
This is not work at visual mode T_T

**Comment by run27017** [comment]
> **Note for anyone finding this closed issue in the future:**
> 
> @xream [added hooks to NERDCommenter](https://github.com/scrooloose/nerdcommenter/pull/249) to allow switching to different comment delimiters, depending on the region of the `.vue` file.
> 
> Add the following to your `.vimrc` to enable it:
> 
> ```viml
> let g:ft = ''
> fu! NERDCommenter_before()
>   if &ft == 'vue'
>     let g:ft = 'vue'
>     let stack = synstack(line('.'), col('.'))
>     if len(stack) > 0
>       let syn = synIDattr((stack)[0], 'name')
>       if len(syn) > 0
>         let syn = tolower(syn)
>         exe 'setf '.syn
>       endif
>     endif
>   endif
> endfu
> fu! NERDCommenter_after()
>   if g:ft == 'vue'
>     setf vue
>     g:ft
>   endif
> endfu
> ```

The code does not work well for below code:

```vue
<template>
  <div>
    <i-col>
      <p>haha</p>
    </i-col>
  </div>
</template>

<script>
export default {
  data () {
    return {}
  }
}
</script>
```

If I invoke `<leader>cc` for some lines, it produce below comments (with `/* */`)

```vue
<template>
  <div>
    <i-col>
      /*<p>haha</p>*/
    </i-col>
  </div>
</template>

<script>
export default {
  data () {
    /*return {}*/
  }
}
</script>
```
