### ISSUE TITLE
No syntax highligthing at all.

### ISSUE THREAD

**Issue by jesusvazquez** [posva/vim-vue#19]
:PluginList
```
Plugin 'VundleVim/Vundle.vim'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'scrooloose/nerdtree'
Plugin 'mileszs/ack.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-fugitive'
Plugin 'bling/vim-airline'
Plugin 'majutsushi/tagbar'
Plugin 'tpope/vim-commentary'
Plugin 'arnaud-lb/vim-php-namespace'
Plugin 'elzr/vim-json'
Plugin 'othree/html5.vim'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'digitaltoad/vim-pug'
Plugin 'posva/vim-vue'
Plugin 'xsbeats/vim-blade'
```
vim --version
```
vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 29 2016 11:28:12)
```

After installing the plugin vim said "Done!" and the a valid vue file is not getting highlighted. I did checked the other issues, my file is properly spelled like "profile.vue".

I did also run the following: 
```
source ~/.vim/bundle/vim-vue/syntax/vue.vim
run ~/.vim/bundle/vim-vue/syntax/vue.vim
```
But I didn't get any output, not even errors. 

Any ideas?

**Comment by posva** [comment]
try `set ft=vue`

**Comment by jesusvazquez** [comment]
Yes with that it works nice. Why is the ftdetect not working?

**Comment by posva** [comment]
It may be about cache, I've already experienced this issue with other plugins. It should be working fine with files that have not be opened before

**Comment by jesusvazquez** [comment]
Well It's not, I tried lastnight with a new *.vue file but it didnt work either. Any idea?

**Comment by posva** [comment]
You may have a conflicting command somewhere else

**Comment by jesusvazquez** [comment]
I didnt find the conflicting command so I just edited $VIMRUNTIME/scripts.vim and i added: 

```
  " Vue files
  elseif s:line1 =~ '^<template>*'
    set ft=vue
```

Since all my vue files start with template vim will set the ft automatically.

Cheers.

**Comment by MaxHill** [comment]
You can also check for the .vue filetype, like this:
```
" Vue syntax highligting
autocmd BufNewFile,BufRead *.vue set ft=vue
```
