### ISSUE TITLE
it dosent work for me 

### ISSUE THREAD

**Issue by motecshine** [posva/vim-vue#27]
env: spf13-vim 

![image](https://cloud.githubusercontent.com/assets/7615270/18960759/691ef832-869d-11e6-9f37-db1d31a22c70.png)

**Comment by posva** [comment]
Try `set ft=vue`. 
Other than that I cannot help you if you don't provide more information

**Comment by motecshine** [comment]
thks a lot, set ft=vue , the plugin will be work
