### ISSUE TITLE
Beautifier for .vue files?

### ISSUE THREAD

**Issue by janimo** [posva/vim-vue#33]
What would it take to have support for formatting/beautifying the scripts within .vue files?

**Comment by posva** [comment]
You'll have to beautify each part of the file separately 😄

**Comment by janimo** [comment]
Thanks, I figured if there is a way to separate the bits in the .vue file (this is what eslint-plugin-vue does) and there are tools for beautifying js... :)

**Comment by janimo** [comment]
At least for the script part this is good enough for now :)
standard --fix seems to be better at this than either eslint --fix or standard-format

autocmd BufWritePre *.vue :/<script>/+1,/<\/script>/-1 !standard --fix --stdin

**Comment by andreiglingeanu** [comment]
What about supporting prettier? In https://github.com/prettier/prettier/issues/651 they state the fact that editors are responsible for handing JavaScript parts from files with special syntaxes.

**Comment by adriaanzon** [comment]
We may be able to configure a fixer for [ALE](https://github.com/w0rp/ale), as it supports fixing now. I'm not entirely sure how to go about fixing a range of lines, but we can probably just leave the unrelated lines as they are.

**Comment by MaraniMatias** [comment]
I am using [vue-formatter](https://www.npmjs.com/package/vue-formatter), you need node js

**Comment by sammckay10** [comment]
Hi, 

I managed to get Standard formatting the JS, HTML beautify formatting the template and Sass Convert formatting the SCSS.

Install dependencies
`gem install sass`
`npm install -g standard html-beautify`

And then add the following to your .vimrc

" Use Standard to format the between script tags
autocmd BufWritePre *.vue silent! :/<script>/+1,/<\/script>/-1 !standard --fix --stdin
" Use HTML Beautify to format between template tags
autocmd BufWritePre *.vue silent! :/<template>/+1,/<\/template>/-1 !html-beautify --stdin
" Use Sass Convert to format SCSS between style[lang=scss] tags
autocmd BufWritePre *.vue silent! :/<style lang="scss">/+1,/<\/style>/-1 !sass-convert --from scss --to scss --stdin

**Comment by weilbith** [comment]
@sammckay
Do I have to use these packages or is there the possibility to use _Vim_ defaults syntax highlighting but for the separated sections?

**Comment by weilbith** [comment]
Okay, following this approach, it works for html. JS is kinda okay. A lot is simply the same color and could be more differentiated. And Sass does not work for me.

**Comment by andreiglingeanu** [comment]
Okay guys, let's party, prettier added support for `.vue` files out of the box https://github.com/prettier/prettier/pull/3563 🎉

**Comment by posva** [comment]
Closed since this was added to prettier
