### ISSUE TITLE
Syntax highlighting doesn't work

### ISSUE THREAD

**Issue by itsjef** [posva/vim-vue#34]
Hmmm, I don't know why but the my highlighting doesn't seem to work correctly :(

**Screenshot:**
![vue](https://cloud.githubusercontent.com/assets/1902587/19923455/0ed8cbae-a11a-11e6-920d-0cfa3dc91da7.png)

I'm using **Neovim** 0.1.6 and [othree/yajs.vim](https://github.com/othree/yajs.vim
) as well as [mxw/vim-jsx](https://github.com/mxw/vim-jsx
) to highlight my .js, .jsx files.

**Comment by posva** [comment]
I'm sorry but I don't see how to help you there :(

**Comment by itsjef** [comment]
mmmm...kay, so closest I managed to work it around by putting:
```vimL
au BufRead,BufNewFile *.vue set ft=javascript.jsx
```
into my .vimrc, which force-transform the filetype and then highlighted by **yajs** and **vim-jsx**

Screenshot after:
![vue](https://cloud.githubusercontent.com/assets/1902587/19954143/31080d78-a1a8-11e6-8848-04bc0725789a.png)

**Comment by posva** [comment]
Glad you found your way! Indeed, using the html5.vim is a working alternative to vue-vim when dealing with HTML, CSS and Javascript.
It won't work well if using jade, coffee or any preprocessor
