### ISSUE TITLE
Issue saving a .vue file

### ISSUE THREAD

**Issue by nathasm** [posva/vim-vue#44]
The first time I try to save/modify a .vue file I get the following error:
```
Error detected while processing function <SNR>46_BufWritePostHook[3]..<SNR>46_UpdateErrors[13]..<SNR>46_CacheErrors[26]..64[2]..SyntaxCheckers_vue_eslint_IsAvailable:
line    8:
E716: Key not present in Dictionary: getVersion(), [0, 1])
E116: Invalid arguments for function syntastic#util#versionIsAtLeast(self.getVersion(), [0, 1])
E15: Invalid expression: g:syntastic_vue_eslint_generic || syntastic#util#versionIsAtLeast(self.getVersion(), [0, 1])
```

This is using vim8 installed via vundle.

Any thoughts?

**Comment by posva** [comment]
I tried with vim8, vundle and syntastic , all updated and couldn't reproduce it. Have you updated your plugins

**Comment by nathasm** [comment]
*facepalm* I issued a BundleInstall and didn't follow-up with a BundleUpdate. Sorry for the noise.

**Comment by posva** [comment]
No worries. btw it should be `PluginInstall` and `PluginUpdate`. I think that `Bundle*` got deprecated some time ago
