### ISSUE TITLE
syntax highlighting stops too often

### ISSUE THREAD

**Issue by bernhardreiter** [posva/vim-vue#48]
Using vim-vue for a while now, I've noticing too often that syntax highlighting stops in more complex files
so that parts of the file are not highlighted anymore. It does not behave consistently, it depends where I jump into the file and then from where I am scrolling. I guess that there are probably several sources for the bad behaviour, but in total it reduces the usefulness of vue-vim a lot, thus I'm opening this issue.

I' using stock debian vim with vim-vue and just updated to f6694b40a7baaf72c7f3ea743f2ae2fbf39918b2
```
LANG=C vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 17 2016 06:34:13)
Included patches: 1-488, 576
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
```

Are there standard hints how to further analyse and report such problems with syntax highlighting rules?

**Comment by adriaanzon** [comment]
This is because Vim tries to highlight text in an efficient way. Especially in files that include multiple different languages, it can get confused.

To work around this, you can run `:syn sync fromstart` when it happens. I personally have setup a mapping for this.

See `:h :syn-sync-first` and this article http://vim.wikia.com/wiki/Fix_syntax_highlighting

**Comment by posva** [comment]
Thanks a lot for the answer @adriaanzon ! I didn't know

**Comment by bernhardreiter** [comment]
Thanks @adriaanzon that seem to help in my first tries. It seems strange that this happens more with .vue files than with other files I am working with in vim. Maybe the default coming with vim-vue should be changed. Most single file components are rather short, so `:syntax sync fromstart`  seems to be a sensible default.

**Comment by floscr** [comment]
As a workaround i put this in my vimrc

```vim
au BufEnter *.vue syn sync fromstart
```

This fixes the issue for me, i dont know what the drawbacks would be though…
