### ISSUE TITLE
Support for more templating languages?

### ISSUE THREAD

**Issue by tylucaskelley** [posva/vim-vue#50]
The syntax highlighting isn't very helpful as of now and doesn't seem to have the capabilities of other editor's Vue plugins; this is what I get when trying to use Sass and Handlebars for templates:

![screen shot 2017-02-17 at 11 46 31 am](https://cloud.githubusercontent.com/assets/5448759/23074456/c0d104b2-f506-11e6-87e3-400ed8692f15.png)

Just not sure why there's no highlighting on any of the tags, save for the content inside quotes for the style tag.

**Comment by adriaanzon** [comment]
Maybe we can automatically determine the language based on the value of the `lang` attribute, so it can support any language without much effort. 

Vim-markdown does something similar: https://github.com/plasticboy/vim-markdown#fenced-code-block-languages

**Comment by tylucaskelley** [comment]
Yeah that could be helpful, also sorry @posva for the lack of specificity in this issue. Would try to submit a PR but short on time at the moment

**Comment by posva** [comment]
That's ok. Yeah, a PR would be great! I actually don't know how to do it

@adriaanzon Do you want me to add you to the repo?

**Comment by adriaanzon** [comment]
I'm also not really sure if it is possible to make fully automatic, but we can at least make the process of adding a new language as simple as specifying the tag (template/style/script) and the language.

@posva That would be awesome! :smile:

**Comment by adriaanzon** [comment]
@tylucaskelley I added an easier way to register new languages, and I added [this line here that registers syntax for handlebars](https://github.com/posva/vim-vue/blob/f72aac329acad4ed8401df1df2f2fc1a2a7e1a9f/syntax/vue.vim#L45) but since I'm not so familiar with handlebars, can you confirm if it works now?
