### ISSUE TITLE
Screen bugs...

### ISSUE THREAD

**Issue by MIRAMAXED** [posva/vim-vue#51]
I have some unexpected selection when working with *.vue files.
If I type :colorscheme default or :colorscheme solarized, the selection disappears.

![2017-03-01_13-15-29](https://cloud.githubusercontent.com/assets/5852641/23457611/51b17c90-fe81-11e6-8823-72050f6c556d.jpg)

How to fix that so I won't have the unwanted selection when opening *.vue files?

**Comment by posva** [comment]
Hey, it looks like you have some plugin that does that but I really don't know what it can be

**Comment by adriaanzon** [comment]
The inverted color is supposed to be an italic font (it only happens inside of the `<i>` tags).

It has to do with your terminal. It either doesn't support italics, or it doesn't have correct terminfo. Maybe the answers on [this stackoverflow question](http://askubuntu.com/questions/492592/can-i-get-italics-in-gnome-terminal) can help.

**Comment by MIRAMAXED** [comment]
@adriaanzon Thank You for the information! In .vimrc i added few lines:

let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
highlight Comment cterm=italic

Now all works fine!
