### ISSUE TITLE
Error opening .vue files

### ISSUE THREAD

**Issue by jacoborus** [posva/vim-vue#56]
I am not using TypeScript but receive this error when opening any `.vue` file

```
Error detected while processing ~/.config/nvim/plugged/vim-vue/syntax/vue.vim:
line   53:
E484: Can't open file syntax/typescript.vim  
```

**Comment by posva** [comment]
Sorry for that, I missed that when reviewing

**Comment by posva** [comment]
I tried to do it fast, but it's obviously not fixed yet 😆

**Comment by jacoborus** [comment]
That was quick! thank you
