### ISSUE TITLE
Error when opening .vue files, HTML syntax highlighting broken

### ISSUE THREAD

**Issue by tverghis** [posva/vim-vue#57]
Hi,

I just installed this plugin and opened the App.vue file generated by vue-cli, and I see this error:

```
"src/App.vue" 23L, 387C
Error detected while processing /Users/tarun/.vim/bundle/vim-vue/syntax/vue.vim:
line   34:
E65: Illegal back reference
E475: Invalid argument: html keepend start=/^<template\( lang=\("\|'\)[^\1]*html[^\1]*\1\)\?>/ end=/^<\/template>/ contains=@HTML 
fold
```

The syntax highlighting of the HTML part of the .vue file isn't working at all.

How do I address this? I'm new to Vim, so this is all a bit new to me.

Thanks!

**Comment by adriaanzon** [comment]
I don't get this error but it looks like the `\1` back reference are meant for the second capturing group, so the first group should be updated to be non-capturing.

@posva any reason to not use `\_[^>]*` instead here?

**Comment by posva** [comment]
No, my bad sorry. I should have left the html part as it was or add what you said to let any attr go through. Feel free to fix it on master, I'm on a train right now

**Comment by adriaanzon** [comment]
@tverghis I pushed a commit to fix this, is the html part of your .vue file highlighted correctly now?

**Comment by posva** [comment]
Don't worry, that's how it should be. This was the commit that changed that: https://github.com/posva/vim-vue/commit/404787aae2980ef26dbeb24b5e6af29e0a442f1a

**Comment by tverghis** [comment]
@adriaanzon @posva thanks, the error is fixed now.

On an unrelated note, do you happen to know why the syntax highlighting for the `style` tag looks broken?

<img width="890" alt="vim-vue" src="https://cloud.githubusercontent.com/assets/3781734/23949837/db080268-0956-11e7-87b8-3f7e9949cb1a.png">

The actual CSS itself seems fine.

Here are my vim plugins:
```
/Users/tarun/.vim/bundle
├── html5.vim
├── nerdtree
├── tsuquyomi
├── typescript-vim
├── vim-airline
├── vim-colors-solarized
├── vim-javascript
├── vim-vue
```

and my `.vimrc` file:
```VimL
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown
au BufRead,BufNewFile *.vue setlocal shiftwidth=2 tabstop=2

execute pathogen#infect()
syntax on 
filetype plugin indent on
let g:javascript_plugin_jsdoc = 1

set background=dark
colorscheme solarized 

set relativenumber

set laststatus=2
set ttimeoutlen=50
```

It happens regardless of which theme I use.

Thanks again

**Comment by adriaanzon** [comment]
@tverghis This is because the language regions don't include the necessary syntax groups to highlight HTML tags.

I'm working on an easier way to define new languages on the `register-function` branch: https://github.com/posva/vim-vue/commit/30a920f7653601a6bf01a601cf86a0c900c3c1e5. This will also make it easier to add these sorts of changes, so expect to see this fixed in the near future :)

**Comment by adriaanzon** [comment]
Fixed this in 6b08ed4 (not in master yet)

**Comment by posva** [comment]
hey @adriaanzon I set up circleci since you seem to be adding test (which is amazing, I didn't know it was possible). You should have the rights to rebuild, ping me if you need anything

**Comment by adriaanzon** [comment]
Ah, great, I was already planning to do that but I didn't really know how, I've never set that up before. I'll add a circle.yml and see how it goes.

**Comment by posva** [comment]
I searched really fast, and it looks like the example on the Vader repository works out of the box for travis and circle ci too.
I set it up on a branch test-ci. Feel free to merge it or reuse the two files. We'll end up keeping only one build system, I vote to keep the fastest one 😛 
You can test around and check at https://circleci.com/gh/posva/vim-vue and https://travis-ci.org/posva/vim-vue

**Comment by adriaanzon** [comment]
The example on the Vader repo works for plugins that don't require any other plugins. I already created an install script and vimrc to use for testing.

I'll go ahead and try it out on travis, to see which one is faster 🙂

**Comment by posva** [comment]
Yeah, it may be cleaner to create a vimrc for testing in the test folder. I haven't checked much. I'll let you have fun and do as you wish 😄

**Comment by adriaanzon** [comment]
They both seem to end at around the same time. Travis says it is faster but it doesn't record the boot time 😛
 Let's just stick with CircleCI then.

**Comment by posva** [comment]
Ok, I just reverted my commit on master, but let the other branch there. Delete it when needed 🙂
