### ISSUE TITLE
Setting commentstring to something else

### ISSUE THREAD

**Issue by mcmillion** [posva/vim-vue#58]
I've been trying to change the commentstring for Vue syntax (since I usually want to comment/uncomment JS and not HTML). I can't seem to get it to work. I assume it's because of the load order, but I may be wrong. Any ideas?

**Comment by adriaanzon** [comment]
What plugin do you use for commenting?

**Comment by mcmillion** [comment]
I use vim-commentary.

**Comment by adriaanzon** [comment]
Commentary only supports one filetype at a time. You may want to use something like [tcomment](https://github.com/tomtom/tcomment_vim) or [nerdcommenter](https://github.com/scrooloose/nerdcommenter) to be able to comment different filetypes in one file.

See also https://github.com/tpope/vim-commentary/issues/60#issuecomment-183060569.

**Comment by mcmillion** [comment]
_Ahhhh_, it all makes sense now. Switching to tcomment worked beautifully, thanks!
