### ISSUE TITLE
Use of template conditionals breaks highlighting

### ISSUE THREAD

**Issue by bmcorser** [posva/vim-vue#6]
Use of what I imagine is a fairly common feature http://vuejs.org/guide/conditional.html#Template_v-if breaks highlighting (the behaviour is as if the outer `template` block is over).

Example:
<img width="653" alt="screen shot 2016-01-30 at 12 34 49" src="https://cloud.githubusercontent.com/assets/1449387/12695710/a8acb28c-c74e-11e5-9bf5-e74af2f17ee7.png">

**Comment by posva** [comment]
mmh I guess adding a regex at https://github.com/posva/vim-vue/blob/master/syntax/vue.vim#L39 to the end `end=/^</template>/` should make this work. I'll give it a try later when I can :smile:

**Comment by bmcorser** [comment]
Not sure. How to detect how many `template` elements have been nested?

**Comment by posva** [comment]
That trick seems to work :smile:

**Comment by bmcorser** [comment]
:+1: ty
