### ISSUE TITLE
When press `G`, then long press `k` key, it will be very slow.

### ISSUE THREAD

**Issue by colorwin** [posva/vim-vue#60]
When I press `G` go to bottom, then long press `k` key go up, vim will be very slow.
I test this in normal '.js' or '.css', it is fast,
I use `spf13-vim`, and add this line in my '.vimrc.bundles.local' and install it:
```
Bundle 'posva/vim-vue'
```

**Comment by adriaanzon** [comment]
Can you paste the output of `:verbose autocmd CursorMoved`?

**Comment by colorwin** [comment]
`:verbose autocmd CursorMoved` output seem not helpful. Because in '.js' or '.css' file, output is same.

In a '.vue' file, it was not hightlihgt, so I `:set  syntax=vue`, it become dalay. And I `:set syntax=html`, it is also delay. But I `:set syntax`, it is fast.

Then I google and find this is [Neocomplcache problem](https://github.com/spf13/spf13-vim/issues/275).

**Comment by colorwin** [comment]
Unfortunatly, it is not that problom.
I found a relative [stackoverflow](http://stackoverflow.com/questions/19030290/syntax-highlighting-causes-terrible-lag-in-vim). I try all the method in it,  but it is useless.
If I set syntax as 'js' or 'css', it is fast. If 'html', it is a little slow. If 'vue', it is very slow, when long press `hjkl ` key. But if I press key like `k` , `k`, `k`, it is OK. 

By the way, `%` not work.

`:syntime on`,  `:syntime report` result:
```
TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
  0.070791   7995   1447    0.000092    0.000009  cssMediaProp       \(\(max\|min\)-\)\=\(height\|width\|resolution\|monochrome\|color\(-index\)\=\)
  0.069179   7995   1447    0.000127    0.000009  cssMediaProp       \(\(max\|min\)-\)\=\(height\|width\|resolution\|monochrome\|color\(-index\)\=\)
  0.068640   7995   1447    0.000070    0.000009  cssMediaProp       \(\(max\|min\)-\)\=\(height\|width\|resolution\|monochrome\|color\(-index\)\=\)
  0.067175   2929   0       0.000503    0.000023  sassProperty       \%([{};]\s*\|^\)\@<=\%([[:alnum:]-]\|#{[^{}]*}\)\+\s*:
  0.066513   7995   1447    0.000222    0.000008  cssMediaProp       \(\(max\|min\)-\)\=\(height\|width\|resolution\|monochrome\|color\(-index\)\=\)
  0.065951   7995   1447    0.000178    0.000008  cssMediaProp       \(\(max\|min\)-\)\=\(height\|width\|resolution\|monochrome\|color\(-index\)\=\)
  0.065526   7995   1447    0.000089    0.000008  cssMediaProp       \(\(max\|min\)-\)\=\(height\|width\|resolution\|monochrome\|color\(-index\)\=\)
  0.060682   4232   421     0.000530    0.000014  jsRegexpString     \%(\%(\%(return\|case\)\s\+\)\@50<=\|\%(\%([)\]"']\|\d\|\w\)\s*\)\@50<!\)/\(\*\|/\)\@!
  0.060645   2929   0       0.000202    0.000021  sassProperty       \%([{};]\s*\|^\)\@<=\%([[:alnum:]-]\|#{[^{}]*}\)\+\s*:
  0.055964   4232   421     0.000181    0.000013  jsRegexpString     \%(\%(\%(return\|case\)\s\+\)\@50<=\|\%(\%([)\]"']\|\d\|\w\)\s*\)\@50<!\)/\(\*\|/\)\@!
  0.055462   4232   421     0.000144    0.000013  jsRegexpString     \%(\%(\%(return\|case\)\s\+\)\@50<=\|\%(\%([)\]"']\|\d\|\w\)\s*\)\@50<!\)/\(\*\|/\)\@!
```

Some other infomation
```
:verbose autocmd CursorMoved
--- Auto-Commands ---
Undotree  CursorMoved
    *         call UndotreeUpdate()
        Last set from ~/.vim/bundle/undotree/plugin/undotree.vim
matchparen  CursorMoved
    *         call s:Highlight_Matching_Pair()
        Last set from /usr/share/vim/vim80/plugin/matchparen.vim
CursorMoved
    *         call <sid>sync_active_winnr()
        Last set from ~/.vim/bundle/vim-airline/autoload/airline/extensions.vim
              call s:update()
        Last set from ~/.vim/bundle/vim-airline/autoload/airline/extensions/wordcount.vim
```

```
:au CursorMoved
--- Auto-Commands ---
Undotree  CursorMoved
    *         call UndotreeUpdate()
matchparen  CursorMoved
    *         call s:Highlight_Matching_Pair()
CursorMoved
    *         call <sid>sync_active_winnr()
              call s:update()
```

**Comment by colorwin** [comment]
If i comment this line in vue.vim, it will be fast although it throw me errors:
```
  "let s:syntaxes = s:search_syntaxes('pug', 'slm', 'coffee', 'stylus', 'sass', 'scss', 'less', 'typescript')
```

**Comment by adriaanzon** [comment]
You mentioned you're using a vim distribution. Since that includes so many plugins, I suspect one of the plugins in that distribution is causing the lag.

Can you try opening a .vue file with only the needed plugins enabled, and see if it is any faster?

If you don't have an easy way to disable plugins, you can try the following: 

Clone this repository and check out the `register-function` branch, which includes an environment to test without any plugins other than the needed ones ([more details here](https://github.com/posva/vim-vue/tree/register-function/test#readme)). To use it, run the `test/install.sh` script, and then open vim with the following command:

```
vim -u test/vimrc YOUR_FILE.vue 
```

**Comment by colorwin** [comment]
In your test, it work normally. I will try to open a .vue file with only the needed plugins enabled.
