### ISSUE TITLE
screenshots help

### ISSUE THREAD

**Issue by alanerzhao** [posva/vim-vue#64]
![image](https://cloud.githubusercontent.com/assets/1327263/24888830/af53f7ec-1e98-11e7-8b75-e04342580108.png)
![Uploading image.png…]()

vimrc config

`
Plugin 'posva/vim-vue'
"molokai 配色
let g:molokai_original = 1
let g:rehash256 = 1
" react jsx
let g:jsx_ext_required = 0

let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

let g:ycm_error_symbol = '>>'
let g:ycm_warning_symbol = '>>'
"let g:ycm_use_ultisnips_completer = 1
"
"SirVer/ultisnips and vim-snippets
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
"
"let g:UltiSnipsUsePythonVersion = 2
let g:UltiSnipsSnippetDirectories=["UltiSnips"]
"let g:UltiSnipsEnableSnipMate=0
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"           "跳到下一个光标点
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
""let g:UltiSnipsExpandTrigger="k"                    "supperTab继承
"" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

" tern_for_vim
let tern_show_signature_in_pum = 1

" make YCM compatible with UltiSnips (using supertab)
"let g:ycm_semantic_triggers =  {
  "\   'c' : ['->', '.'],
  "\   'objc' : ['->', '.'],
  "\   'ocaml' : ['.', '#'],
  "\   'cpp,objcpp' : ['->', '.', '::'],
  "\   'perl' : ['->'],
  "\   'php' : ['->', '::'],
  "\   'cs,java,javascript,d,python,perl6,scala,vb,elixir,go' : ['.'],
  "\   'vim' : ['re![_a-zA-Z]+[_\w]*\.'],
  "\   'ruby' : ['.', '::'],
  "\   'lua' : ['.', ':'],
  "\   'erlang' : [':'],
  "\ }

"javascript 
au FileType html,javascript let g:javascript_enable_domhtmlcss = 1

" 打开javascript折叠
let b:javascript_fold=1
" 打开javascript对dom、html和css的支持
let javascript_enable_domhtmlcss=1

"powerline相对比较麻烦还要安装特殊字休
"参见https://github.com/Lokaltog/vim-powerline/tree/develop/fontpatcher
"let g:Powerline_symbols = 'fancy'

""markdown
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh']
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

""设置语言缩进
autocmd FileType scss,css setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType javascript setlocal expandtab shiftwidth=4 tabstop=4 softtabstop=4 textwidth=80
autocmd FileType html setlocal expandtab shiftwidth=4 tabstop=4 softtabstop=4

" 将指定文件的换行符转换成 UNIX 格式
autocmd FileType php,javascript,html,css,python,vim,vimwiki set ff=unix

" Vue syntax highligting
autocmd FileType vue syntax sync fromstart
" autocmd BufRead,BufNewFile *.vue setlocal filetype=vue.html.javascript.css

"vim-javascript-syntax 语法高亮有bug
"au FileType javascript call JavaScriptFold()

"set modifiable
"" ZenCoding
let g:user_emmet_expandabbr_key='<c-o>'
"let g:user_emmet_mode='n'    "only enable normal mode funcs.
"let g:user_emmet_mode='inv'  "enable all funcs, which is equal to
let g:user_emmet_mode='a'    "enable all func in all mode.
"let g:use_zen_complete_tag = 1
let g:user_emmet_install_global = 0
autocmd FileType html,css,javascript,vue EmmetInstall
""日历
map ca :Calendar<cr>
`

**Comment by posva** [comment]
Sorry, there's not much I can help you with. You can try installing Syntastic and see if that fixes your error or seek for some help on SO. Good luck 🙂

**Comment by adriaanzon** [comment]
It looks like he's already installed Syntastic, but I can't reproduce it either way.

Maybe try reinstalling or updating Syntastic?

**Comment by alanerzhao** [comment]
i am installed Syntastic and eslint-plugin vue
