### ISSUE TITLE
style scss syntax broken

### ISSUE THREAD

**Issue by jsnick** [posva/vim-vue#68]
How can I apply scss syntax in style tag with no attributes or only "scoped" attribute ?
(I use postcss.)

http://imgur.com/a/29kKp

**Comment by posva** [comment]
You should be able to do something like:

```vue
<style nolang="scss">
```

It's not possible to do without attributes

**Comment by jsnick** [comment]
Thank you for answering.

I tried your solution but
`<style nolang="scss">` and `<style lang="scss">` do not work, too.

- My env is OS X, zsh, neovim.
the file extention is *.vue.

- init.vim includes 
```
autocmd BufRead,BufNewFile *.vue setlocal filetype=vue
autocmd FileType vue syntax sync fromstart
```

- style code saved in `test.vue` file
```
<style nolang="scss">
.container {
  .main-title.active {
    color: #868AE5;
  }
  .divider {
    height: 1px;
    margin: 10px 0;
    border-top: 1px solid #eee;
    list-style: none;
    &:last-child {
      border-top: 0;
    }   
  }
  .inputbox {
    color: #FF74F7;
  }
}
</style>
```

- I plug-installed only this `vim-vue` for vuejs.  

- Here my new screenshot with your solution.
http://imgur.com/wFDs2RW

- I have found `&:last-child` in `.container .divider`  has a problem while I'm writing this comment.
This is the screenshot `$:last-child` removed version.
http://imgur.com/TLPWRd3

- and Is there any reason that nested classes has different color from parent class ?
As you can see the screenshot, parent class has green color and nested classes have white color.

**Comment by adriaanzon** [comment]
I can reproduce that, even with `lang="scss"`:

![image](https://cloud.githubusercontent.com/assets/4326420/25803665/3407bd42-33f8-11e7-9c6b-8dbc6a3d9ec4.png)

It looks like it doesn't use the scss highlighting at all, but just uses the highlighting from css.

I have noticed it before though, it just hasn't really bothered me enough. I will have a look at what is causing this soon. My initial guess is that css matches s**css**, but I'm not sure.

**Comment by adriaanzon** [comment]
It's not because `scss` gets matched as `css`, since we don't have those rules set up. Vim-vue inherits the html syntax, which already provides css highlighting. So my initial guess wasn't right.

I use cakebaker/scss-syntax.vim for scss highlighting. I found out that when I remove the [`runtime! syntax/css.vim` lines](https://github.com/cakebaker/scss-syntax.vim/blob/master/syntax/scss.vim#L16-L17), the scss highlighting works perfectly fine in vue files, so it must have to do something with the css syntax file.

**Comment by jsnick** [comment]
Thanks @adriaanzon !  I got to know why.

I use cakebaker/scss-syntax.vim, too.
Temporarily, I modified it and syntax/vue.vim for supporting lang="postcss" (just hard-coding at scss region like `*\(scss|postcss\)` :(  ).

My co-workers use another editors like VS-code, Atom and etc...
Their vue-style-syntax for postcss in each editor need `lang="postcss"`.
And explicit lang attribute of style tag looks better for maintenance.
So we decided to add lang="postcss" to code consistently.

P.s.
Actually, if `lang="postcss"` is nothing, it is loaded well for using [nuxt.js](https://github.com/nuxt/nuxt.js) with [nuxt.config.js - build.postcss](https://nuxtjs.org/api/configuration-build/#postcss). I think this build.postcss config overrides css-loader)

**Comment by acidjazz** [comment]
hmm, i'm having this issue as well, i tried @adriaanzon 's fixed and no dice, i'm using cakebaker/scss-syntax on top of this syntax and sekel-vim-vue-syntastic

**Comment by blieque** [comment]
Is there a tidy solution to this? Do I need to modify my CSS syntax file?

**Comment by dwieeb** [comment]
It appears scss syntax is not applying for me as well (I use cakebaker's scss plugin as well).

![screenshot from 2017-12-16 16-07-16](https://user-images.githubusercontent.com/236501/34074723-3eab1dac-e27b-11e7-809d-ac461a24c3de.png)

@adriaanzon Do you have a set of steps the community can take to work together and resolve this issue? You seem to know the most about it. Will we need to PR `cakebaker/scss-syntax.vim`?

**Comment by adriaanzon** [comment]
Hi @dwieeb, just tuning in to say I haven't forgotten about this 🙂 . I will probably have some time to look at this next month.

**Comment by adriaanzon** [comment]
While trying out [a fix](https://github.com/posva/vim-vue/commit/265f991ec7a0af6bac40db2d07d6accdb152c8d3) for #95, I found out that scss works fine when `syntax/less.vim` isn't loaded.

**Comment by adriaanzon** [comment]
When removing the `runtime! syntax/css.vim` lines from `syntax/less.vim`, scss also works (ref. https://github.com/posva/vim-vue/issues/68#issuecomment-300161558).

What also somehow works is moving LESS to the top of this list: https://github.com/posva/vim-vue/blob/3cc4ac7b02b4ee76a5f16d8b39bf559042f6b266/syntax/vue.vim#L46-L55

**Comment by trev-dev** [comment]
Bookmarking this issue so I can remember what to change when I run my plugin updates xD - I wonder if this would be of interest to @cakebaker in the off-chance event that others would rather see his syntax highlighting for vue vs css.

**Comment by netzego** [comment]
> When removing the `runtime! syntax/css.vim` lines from `syntax/less.vim`, scss also works (ref. [#68 (comment)](https://github.com/posva/vim-vue/issues/68#issuecomment-300161558)).
> 
> What also somehow works is moving LESS to the top of this list:
> 
> https://github.com/posva/vim-vue/blob/3cc4ac7b02b4ee76a5f16d8b39bf559042f6b266/syntax/vue.vim#L46-L55

Strange, i have to move this to the end of the list. Now it's working.

**Comment by liambutterworth** [comment]
Not sure if something has changed since this fix was implemented but I also have to move less to the end of the list to get SCSS syntax highlighting in vue components.

**Comment by pwang2** [comment]
Is there a way without changing the syntax source?  I don't this those workarounds are legit fix.

**Comment by adriaanzon** [comment]
You could try setting the `g:vue_pre_processors` variable to 'detect_on_enter', so it only loads the languages that are needed.

**Comment by metal3d** [comment]
@adriaanzon I tried to set "nolang", "lang", and set `let g:vue_pre_processors="detect_on_enter"` in my nvim init file. I still have bad syntax check:
![image](https://user-images.githubusercontent.com/100080/104334015-2684fa80-54f2-11eb-99d6-4df63508e42a.png)
