### ISSUE TITLE
<script> top portion seems not to be highlighted correctly

### ISSUE THREAD

**Issue by acidjazz** [posva/vim-vue#69]
I might be mistaken by reporting this, but why is < template > different from <style> and <script> is that normal? 

![image](https://cloud.githubusercontent.com/assets/967369/25979331/aa7ab9b2-367c-11e7-91a6-2f72c62a4097.png)

**Comment by adriaanzon** [comment]
Can you confirm you're on the latest version?

**Comment by acidjazz** [comment]
i was not! I just updated and now both are red.. but oddly <script> is behaving now:

![image](https://cloud.githubusercontent.com/assets/967369/25989918/b8ef986a-36b2-11e7-8194-c510bd8b27bd.png)

**Comment by adriaanzon** [comment]
Hmm, does it look like that all of the time? Try this: https://github.com/posva/vim-vue#my-syntax-highlighting-stops-working-randomly

**Comment by acidjazz** [comment]
Yes I tried that, no go. but:

it seems as if vim-stylus was out of date as well, or maybe some other plugins i had, i destroyed `.vim/plugged` and ran a fresh `:PlugInstall`

still its a bit odd that `<script>` is rendering that way

![image](https://cloud.githubusercontent.com/assets/967369/25991660/df390f96-36b8-11e7-9bf2-d4307b21010b.png)

**Comment by acidjazz** [comment]
what's even more odd is if i 

`vi main.styl` the syntax is proper but if i `vi main.vue` w/ stylus, its broken, splitting that with `main.styl` is broken as well.. its as if vue breaks stylus syntax..

**Comment by acidjazz** [comment]
@posva yes i agree mostly, the code in the tags work now and i'm happy. just kind of odd how stylus randomly breaks, i'll look more into `vim-stylus`

**Comment by steakknife** [comment]
There's an incompatibility somewhere between NERDTree and vim-vue or one of the deps (all latest plugins and vim).

Editing a .vue directly works, but navigating to it is broken.

**Comment by MaraniMatias** [comment]
I had the same problem, solving it by deleting vim-polyglot

**Comment by adriaanzon** [comment]
I'm not sure if this is still an issue for people but I can't reproduce it myself.

@acidjazz if you're still experiencing the stylus issue, please create a new issue for that.
