### ISSUE TITLE
Indentation rules?

### ISSUE THREAD

**Issue by neagle** [posva/vim-vue#7]
I gave vue components a shot for the first time yesterday, and while the syntax highlighting for different regions seems to be working fine, I don't get any indentation rules. In my set up at least, I get no auto-indentation whatsoever, which is pretty annoying. (I'm using filetype indent settings with `filetype plugin indent on`.)

Is there any possibility of getting vim to adjust indentation settings to match the syntax regions this sets up?

**Comment by posva** [comment]
Can you give an example file to try reproduce it?
While I'm aware indentation doesn't work very well, I've don't have a lot of experience with VimL and I really don't know how to fix that. However I still get the indentation right while editing css, js, jade and coffee.

**Comment by neagle** [comment]
Hm: I wonder why your indentation works. It could very well be something about my vim setup, I guess. Do you have `filetype plugin indent on` in your `.vimrc`?

```
```

**Comment by posva** [comment]
I forgot to say, but yes, as I'm using Vundle I do have the `filetype plugin indent on` in my vimrc

**Comment by neagle** [comment]
Hm: I wonder why your indentation works. It could very well be something about my vim setup, I guess. Do you have filetype plugin indent on in your .vimrc?

This is an example `.vue` file. [Here is my .vimrc file](https://gist.github.com/neagle/d890b7ecc4247d82de22), though I don't really mean to implicate you in my own troubleshooting or what-have-you.

Right now my best thought is just to set up some simple key bindings to switch filetypes on the fly.

```
<style lang="sass">
.some-list {
	padding: 10px;
}
</style>

<template lang="jade">
.some-list
	.row
		.col-xs-12
			h1 Some Things
	.row
		.col-xs-12
			input(
				v-model='searchText'
				v-on:keyup='search'
			)

	.row
		.col-xs-12
			ul
				li(v-for='thing in things')
					a(
						href='{{ thing.user.username }}/{{ thing.slug }}'
					) {{ thing.name }}
					= ' '
					span.version(
						v-if='thing.version'
					) ({{ thing.version }})

</template>

<script>
module.exports = {
	props: [
		'things'
	],
	route: {
		data: function (transition) {
			this.$http({
				url: '/api/things',
				method: 'GET'
			}).then(function (response) {
				this.things = response.data.things;
				this.total = response.data.total;
				transition.next();
			}, function (response) {
				console.log('error', response);
			});
		}
	},
	data: function () {
		return {
			things: [],
			total: '',
			searchText: ''
		};
	},
	methods: {
		search: function () {
			this.$http({
				url: '/api/things',
				method: 'GET',
				params: { search: this.searchText }
			}).then(function (response) {
				this.things = response.data.things;
				this.total = response.data.total;
			}, function (response) {
				console.log('error', response);
			});
		}
	}
};
</script>
```

**Comment by posva** [comment]
I tested the file and everything work as in any other file. I guess I didn't understand well the question.
Indentation partially works, which is, indeed, a shame. I found some clues here http://vim.wikia.com/wiki/User:Ipkiss/Using_vim_to_edit_tips#Comments I'll give it a try tonight :smile:

**Comment by neagle** [comment]
Sorry for not being clearer in my question. I can try to rephrase: in Vim, I've got special indentation rules for different filetypes, so indentation works differently in my JavaScript files from the way it works in Jade files or Sass files.

This plugin works as advertised: it changes the syntax highlighting for different regions of a `.vue` file that combines different languages, but it doesn't change indentation rules (nor does it bring in any of the other things linked to filetype in my vim setup, like linting).

That makes writing JavaScript, especially, in a `.vue` file a really inferior experience to the way it works in its own file.

That's not your responsibility to fix, by any means, I just wondered, since you're someone else clearly using Vim to create and edit Vue files, if you had any thoughts on a possible solution. If multi-language components are going to be a thing going forward, it seems like we Vim users need to figure out a way of bringing all the tools associated with filetype to files with language-specific regions.

**Comment by posva** [comment]
It seems to me that multi region is not well supported in vim (it usually lags with big files). Adding syntastic support should be possible.

Making the plugin better is interesting. I'm open to contributions

**Comment by ijse** [comment]
I solved this problem by adding `Plugin 'othree/html5.vim'`.

**Comment by rleger** [comment]
@ijse Not changing anything for me regarding the indentation inside <template> on a vue filetype.

Could you share a bit more of your setup ?

I currently change the filetype to html to indent inside <template> and to javascript to indent inside <script> which works but is annoying.

**Comment by ijse** [comment]
@rleger Yes, me too. and it works well, dosen't it?

**Comment by neagle** [comment]
Changing the filetype is the only thing that really deals with the issue, as it brings in not just proper indentation, but filetype-based tools like snippets, linting, etc. But that's really clumsy.

Assigning the filetype switch to some kind of shortcut improves things slightly, but it'd still be a lot better if there were some way of dynamically switching it.

**Comment by rleger** [comment]
@neagle exactly. 

I wish vim could handle multiple languages in a single file better. I don't fully understand the difference between syntax and filetype though. 
A filetype can have multiple syntax regions but the indentation and other language specific features seems to be ignored.

I have to look a bit more into syntax

**Comment by posva** [comment]
@rleger don't forget to create a PR if you find a solution :smile:

**Comment by nivv** [comment]
Just started using vim yesterday and I came across this issue as well. As stated before it works fine with files with `.html`-extensions but not with `.vue`. 

I installed `othree/html5.vim` and then added below in my `.vimrc`:

```
au BufRead,BufNewFile *.vue set filetype=html
```
Which sets the filetype to `html`. Now indent works as expected and highlight works nicely too. 

![image](https://cloud.githubusercontent.com/assets/4033930/13915181/57adaa94-ef53-11e5-85a6-4c7b18ce54b0.png)

**Comment by rleger** [comment]
@nivv Highlighting isn't perfect but to me it's the best solution yet, thank you for sharing.

**Comment by posva** [comment]
Good new @neagle! #23 will fix this!

**Comment by samiconductor** [comment]
`set filetype=vue.html` did the trick for me. Gives me the region highlighting from this plugin and the indent rules of html 👍
