### ISSUE TITLE
word wrap

### ISSUE THREAD

**Issue by VinceFanZ** [posva/vim-vue#70]
.vimrc

set nowrap
Plug 'posva/vim-vue'

set nowrap  failure
<img width="868" alt="2017-06-15 4 16 23" src="https://user-images.githubusercontent.com/7631809/27172114-af27ba1a-5179-11e7-9225-b4c3272eb2f3.png">
<img width="715" alt="2017-06-15 4 16 41" src="https://user-images.githubusercontent.com/7631809/27172115-b0684138-5179-11e7-937e-c0134bf69d7c.png">

**Comment by posva** [comment]
you proly did `set tw=80` or similar. Do `set tw=0` to remove the horizontal limit, but this is unrelated to vim-vue
