### ISSUE TITLE
<template> hilight mustaches

### ISSUE THREAD

**Issue by last-partizan** [posva/vim-vue#71]
Can we have js-expression hilighting inside `{{ }}`?

Something like htmldjango but for vue templates.
![s1](https://user-images.githubusercontent.com/301015/27178418-cb89d98c-51d2-11e7-9cca-b0efbc8c6629.png)

**Comment by adriaanzon** [comment]
I've wanted to do this for quite some time. I also tried it locally:

```vim
syntax region vueMustache start=/{{/lc=2 end=/}}/me=e-2 contains=@htmlJavaScript contained
syntax match vueMustacheStart /{{/ nextgroup=vueMustache
syntax match vueMustacheEnd /}}/
highlight link vueMustacheStart Delimiter
highlight link vueMustacheEnd Delimiter
```

But the above only works reliably with pangloss/vim-javascript.

I'll try some more things, until I find something that works with both pangloss/vim-javascript and the default javascript syntax shipped with Vim.

**Comment by last-partizan** [comment]
How do i test this locally?

**Comment by adriaanzon** [comment]
Add it to `syntax/vue.vim`, wherever that is located. For me it's in `~/.vim/plugged/vim-vue/syntax/vue.vim`

**Comment by last-partizan** [comment]
Nice, it works with yajs.vim
