### ISSUE TITLE
Load time is a bit long

### ISSUE THREAD

**Issue by VinceFanZ** [posva/vim-vue#73]
![5874758c-bbae-40ec-a549-6f514e4df7d1](https://user-images.githubusercontent.com/7631809/27646046-3ee5af96-5c5a-11e7-9595-be75c47ef489.png)

Loading time accounts for a third.  How to shorten the?

![276d5877-1a36-45af-836d-c84158ac5746](https://user-images.githubusercontent.com/7631809/27647238-7b69730a-5c5d-11e7-9f61-1cf3b3ab9079.png)

Hope the method name also support highlighted.

**Comment by posva** [comment]
About the load time, there's not much to do. It runs instantly for me...
The syntax coloring depends on the js plugin you use. I don't even remember if the property keys are highlighted
