### ISSUE TITLE
Standard linting rules break indentation

### ISSUE THREAD

**Issue by Ravencrow** [posva/vim-vue#74]
Hi, Everyone!

I'm using standard rules for linting. I use no semicolon, and my indentation is like this:
```
    filters: {
      clock (time) {
        const minutes = parseInt(time / 60)
          const seconds = parseInt(time % 60)
            return `${minutes}:${seconds}`
      }
    }
```
But if I use semicolons, everything goes ok:
```
    filters: {
      clock (time) {
        const minutes = parseInt(time / 60);
        const seconds = parseInt(time % 60);
        return `${minutes}:${seconds}`;
      }
    }
```

What could be happening?

Thanks for this awesome plugin!

**Comment by posva** [comment]
Hey thanks!
That's really weird, it works well for me. Don't you have the same issue with raw js? Could you try removing other plugins to see what is causing it?

**Comment by Ravencrow** [comment]
Oh, it's true! jason0x43/vim-js-indent is the plugin incompatible with this one. Ok, I think I should load that only with js files, not vue.
Thanks!
