### ISSUE TITLE
Vue syntax highlighting slows down Vim a lot

### ISSUE THREAD

**Issue by paxy97** [posva/vim-vue#75]
When loading a vue file vim sets the ft to `vue.html.javascript.css`, which slows down Vim massively, including cursor movement. When setting the ft to `html.javascript.css` it doesn't slow down, so it must be the vue type's fault.

Here's a list of all the Plugins I have installed (not all are loaded)

- SimpylFold: OK (not loaded)
- fzf: OK
- vim-devicons: OK
x vim-polyglot:
    Invalid tag: v2.15.1 (expected: ). Try PlugUpdate.
- indentLine: OK (not loaded)
- rainbow_parentheses.vim: OK (not loaded)
- vim-rsi: OK
- vim-nerdtree-syntax-highlight: OK (not loaded)
- incsearch-fuzzy.vim: OK (not loaded)
- nginx-vim-syntax: OK
- vim-autoformat: OK (not loaded)
- vim-better-default: OK
- tagbar: OK (not loaded)
- vim-easy-align: OK (not loaded)
- vim-cpp-enhanced-highlight: OK (not loaded)
- YouCompleteMe: OK (not loaded)
- asyncrun.vim: OK (not loaded)
- vim-closetag: OK
- vim-move: OK (not loaded)
- gv.vim: OK (not loaded)
- vim-template: OK
- ack.vim: OK
- vim-airline-themes: OK
- gruvbox: OK
- vim-gitgutter: OK
- unite.vim: OK
- incsearch.vim: OK (not loaded)
- vim-airline: OK
- vim-clang-format: OK (not loaded)
- editorconfig-vim: OK (not loaded)
- vim-choosewin: OK
- YCM-Generator: OK (not loaded)
- fzf-filemru: OK (not loaded)
- nerdtree: OK (not loaded)
- nerdtree-git-plugin: OK (not loaded)
- vim-fugitive: OK
- rename.vim: OK (not loaded)
- vim-indent-guides: OK (not loaded)
- tabular: OK (not loaded)
- vim-better-whitespace: OK (not loaded)
- ale: OK
- html5.vim: OK (not loaded)
- fzf.vim: OK
- vim-tmux-navigator: OK
- vim-jsx: OK (not loaded)
- space-vim-dark: OK
- vim-swoop: OK
- PKGBUILD.vim: OK
- python-mode: OK (not loaded)
- rainbow: OK
- emmet-vim: OK
- vim-surround: OK
- vim-multiple-cursors: OK
- auto-pairs: OK
- vim-javascript: OK (not loaded)
- nerdcommenter: OK (not loaded)

This issue occurs on both Vim and NeoVim, both on pretty much the newest versions since I'm running Arch.

I'll be happy to provide more needed information, just tell me what.

**Comment by posva** [comment]
If you can try switching off almost everything and then, turn on progressively things until it slows down, you'll probably be able to detect the slowing down repo.
This is probably not coming directly from vim-vue

**Comment by paxy97** [comment]
I have disabled all the modules and even after enabling all of them again the issue seems to be gone. I have no idea how or why, but thank you. Closing this.
