### ISSUE TITLE
duplicate syntax highlighting regex statements bogging down vim

### ISSUE THREAD

**Issue by jmerizia** [posva/vim-vue#78]
I noticed that the syntax highlighting in this plugin slows my editor down immensely, making it unusable. After running `syntime on` and `syntime report`, I found that for css, the same regex statements were being executed needlessly. I dug into the problem slightly, and found that removing the lines in `syntax/vue.vim`, where `register_language` is called for styling languages, "fixes" the issue. Obviously, this removes support for other styling languages, but it does get rid of the repetition in regex parses. I forked the project and added a conditional statement, so that I could turn off other styling languages in my .vimrc (I only use plain css anyways). However, the issue still persists for those who would like to use scss, less, stylus, etc.

**Comment by posva** [comment]
If there's a way to deactivate some feature checking, we could add that. The easiest way would be to add config variables to skip some checks.

**Comment by jmerizia** [comment]
Ok, I forked the project and did just that. I'll update the readme with appropriate instructions as well.

**Comment by posva** [comment]
Closed in #79
