### ISSUE TITLE
Snippets don't work

### ISSUE THREAD

**Issue by noscript** [posva/vim-vue#82]
Nothing happens when trying to expand a JS snippet inside `<script>` tag.

Using  [ultisnips](https://github.com/SirVer/ultisnips) engine.

**Comment by adriaanzon** [comment]
Create a `vue.snippets` file in your `~/.vim/UltiSnips` directory with the following contents:

```
extends html, javascript, css
```

**Comment by noscript** [comment]
That works, thanks!

**Comment by JesseLeite** [comment]
👌  Was helpful thank you!
