### ISSUE TITLE
Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag [Error]

### ISSUE THREAD

**Issue by daniel-medina** [posva/vim-vue#83]
![screenshot_2017_08_23_12_27_32](https://user-images.githubusercontent.com/13499662/29611571-43dc9f12-87fe-11e7-82df-ac12b7af2e54.png)

I have installed eslint and eslint-plugin-vue, though it was already doing that. This error is overriding other lint errors so I cannot have eslint support while this error is here.

I'm using the latest neovim version, along with all requirements.

**Comment by KrinalPatel11** [comment]
https://icetutor.com/question/parse-error-adjacent-jsx-elements-must-be-wrapped-in-an-enclosing-tag/
