### ISSUE TITLE
I have eror when save the vue file

### ISSUE THREAD

**Issue by dmlzj** [posva/vim-vue#85]
处理 function 424..374 时发生错误:
第    8 行:
E700: 未知的函数: SyntaxCheckers_vue_eslint_GetLocList
第    9 行:
E700: 未知的函数: SyntaxCheckers_vue_eslint_IsAvailable
处理 function <SNR>97_UpdateErrors..<SNR>97_CacheErrors..427..430..435..379 时发生错误:
第    1 行:
E15: 无效的表达式: self._isAvailableFunc()
E15: 无效的表达式: self._isAvailableFunc()
请按 ENTER 或其它命令继续

**Comment by posva** [comment]
I think it looks like you're missing eslint (`npm i -g eslint-cli`). I also think that the problem comes from this plugin: https://github.com/sekel/vim-vue-syntastic
