### ISSUE TITLE
<style lang="..."> looses highlight

### ISSUE THREAD

**Issue by anvaka** [posva/vim-vue#9]
First of all, thank you for the awesome plugin!

I noticed that syntax highlighting is lost if I set language attribute:

![image](https://cloud.githubusercontent.com/assets/225407/13727488/0d9d7f02-e8a9-11e5-9913-5eba574e44cf.png)

I can reproduce it on `NeoVim 0.1.1`

**Comment by posva** [comment]
Hi! It's not really _my_ plugin, the community contributed a lot :smile:
Use double quotes `"` instead of simple quotes in `lang='stylus'`. The regex is not checking for simple quotes (I don't think it's worth adding complexity to it)

**Comment by anvaka** [comment]
I tried double quotes, but it doesn't work either:

![image](https://cloud.githubusercontent.com/assets/225407/13731213/e3e8c41e-e920-11e5-849e-7cc3e9c3a23a.png)

**Comment by posva** [comment]
@anvaka Are you sure the filetype is applied? `:set ft=vue`

**Comment by mikeifomin** [comment]
I have the same issue
