### ISSUE TITLE
Slows down in JS part

### ISSUE THREAD

**Issue by greysonp** [posva/vim-vue#91]
Hey, thanks for making this! I noticed an issue, however. The further down I am in a .vue file, the slower vim performs. At the top of a file, things are pretty normal. At the bottom of a file, vim is unusably slow. It also seems to be half-way slow in the middle.

I _think_ this may be because CSS parsing is really slow. Because I can get the slowdown to happen on files that are less than a full screen in height, and if I delete the style portion, performance greatly improves.

I'm running Vim 8.0 on Arch Linux.

Thanks!

**Comment by levthedev** [comment]
Try setting `78 g:vue_disable_pre_processors=1` like the README says. Worked fine for me!

**Comment by greysonp** [comment]
Aha, thank you! This worked just fine. I apologize for not reading the README better :) 
Can confirm that setting that flag also works when using this plugin via [vim-polyglot](https://github.com/sheerun/vim-polyglot).
Thanks!
