### ISSUE TITLE
Highlight can not work

### ISSUE THREAD

**Issue by yzfdjzwl** [posva/vim-vue#92]
* I use vundle to install it.
*  when I vim `somefile.vue`, I find it does't work.
![a670cfb5eaa00f0c6550ff82dae0fe64](https://user-images.githubusercontent.com/21030370/33355919-890d5c32-d4f4-11e7-93f2-36ee1836419c.jpg)

**Comment by yzfdjzwl** [comment]
There's my `.vimrc`.
![111111111](https://user-images.githubusercontent.com/21030370/33356024-24f4579a-d4f5-11e7-8230-21cdfc1b187b.jpg)

**Comment by yzfdjzwl** [comment]
ok, I find the solution, just add `autocmd BufRead,BufNewFile *.vue setlocal filetype=vue.html.javascript.css` to `.vimrc`

**Comment by sysRQrol** [comment]
I have the same issue, but adding `autocmd BufRead,BufNewFile *.vue setlocal filetype=vue.html.javascript.css` doesn't do anything.
