### ISSUE TITLE
Incorrect highlighting

### ISSUE THREAD

**Issue by SkylerHu** [posva/vim-vue#96]
The grey color is incorrect when i use `vim-vue`.
but that's ok when i change "i-input" to "Input". I was very confused.
![](http://img.momocdn.com/feedimage/A3/A1/A3A1BC80-CCA9-46CC-B41E-0795B155E65620180125.png)

my part of vimrc like this
```
"powerline
set guifont=PowerlineSymbols\ for\ Powerline
set nocompatible
set t_Co=256
let g:Powerline_stl_path_style = "full"

autocmd BufNewFile,BufRead *.vue set ft=vue
autocmd FileType vue set ai
autocmd FileType vue set sw=2
autocmd FileType vue set ts=2
autocmd FileType vue set sts=2
```
vim version
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 20 2017 16:59:31)
MacOS X (unix) version
```

**Comment by posva** [comment]
I imagine adding some extra check at https://github.com/posva/vim-vue/blob/master/syntax/vue.vim#L57 should fix this but I may wrong

**Comment by adriaanzon** [comment]
Since Vue doesn't enforce W3C rules for custom tag names, we should add something like [this](https://github.com/othree/html5.vim/blob/8ec5af02b0ef5f68020dac6f977d1db41c0d7c8c/syntax/html.vim#L78-L80) but simply allow any combination of hyphens, letters, and uppercase letters.
