### ISSUE TITLE
Indentation issues

### ISSUE THREAD

**Issue by sergafts** [posva/vim-vue#98]
It might be that I haven't setup something right, but I am facing indentation issues in `.vue` files.

If I understand correctly (by taking a glance at `/indent/vue.vim`) the plugin tries to split the file into sections and indent differently the `<script>` / `<template>` sections using the indentation rules setup for `javascript` / `html` files by the filetype plugin.

However this doesn't seem to work for me. When I am editing a `.js` file I have 2-space tabs and the expected indentation, but when I'm editing `.vue` files it switches back to 4 spaces.

I tried both indenting the whole file (`gg=G`) and selecting some lines inside the `<script>` tag and indenting only those, but either way it does not work. This doesn't work either when I'm in insert mode and I add a tab, it is (again) 4 spaces.

Am I doing something wrong?

Thank you for your time

**Comment by sergafts** [comment]
```
  shiftwidth=2
        Last set from ~/.local/share/nvim/view/~=+projects=+fixmyride=+app=+javascript=+fixmyride=+src=+App.vue=
```

Looks like there is a stored view for this file. I deleted that, and it worked.
Deleted all the stored views for `.vue` files and it seems to work.

Sorry for bothering you, thanks for the help!

**Comment by RobertTownley** [comment]
In case this helps anyone else, I had to also set `softtabstop=2` to get my indentation rules working as intended (indenting with > worked, but tab didn't until I added that)
